# define the `Secret` to define the necessary environment variables for the mongo server and mongo-express.

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
data:
  mongo-root-username : pes1ug21cs826
  mongo-root-password : bunker@01
